natalsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.PostCreateView.as_view(), name='create'), 
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
     path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='detail-category'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

from datetime import datetime
from django.utils.timezone import now

class Post(models.Model):
    name = models.CharField(max_length=200)
    datepost = models.DateTimeField(default=now, editable=True)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)
    synopsis = models.CharField(max_length=3000)
    distribut = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name} ({self.release_year})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_post = models.DateTimeField(default=now, editable=True)                         
    text = models.CharField(max_length=1000)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name} by {self.author}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comment, Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'release_year',
            'poster_url',
            'datepost',
            'synopsis',
            'distribut',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Data de Lançamento',
            'poster_url': 'URL do Poster',
            'datepost' : 'Atualizado em',
            'synopsis' : 'Sinopse',
            'distribut': "Distribuiçao",
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'date_post',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'date_post' : 'Atualizado em',
            'text' : 'Resenha',
        }

posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Category, Post, Comment, Category
from .forms import PostForm, CommentForm



class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {'post_list': post_list}
    return render(request, 'posts/search.html', context)


class PostCreateView(generic.CreateView):
    model = Post
    template_name = 'posts/create.html'
    fields = ['name', 'release_year', 'poster_url', 'datepost', 'synopsis', 'distribut']
    def get_success_url ( self ) :
        return reverse ('posts:detail', args =(self.object.pk, ) )

class PostUpdateView(generic.UpdateView):
    model = Post
    template_name = 'posts/update.html'
    fields = ['name', 'release_year', 'poster_url', 'datepost', 'synopsis', 'distribut']
    def get_success_url ( self ) :
        return reverse ('posts:detail', args =( self.object.pk, ) )

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    def get_success_url (self) :
        return reverse ('posts:index')

def create_comment( request , post_id ) :
    post = get_object_or_404 ( Post , pk = post_id )
    if request . method == 'POST':
        form = CommentForm ( request . POST )
        if form . is_valid() :
            comment_author = form . cleaned_data ['author']
            comment_date_post = form . cleaned_data ['date_post']
            comment_text = form . cleaned_data ['text']

            comment = Comment( author = comment_author, date_post = comment_date_post, 
            text = comment_text, post = post)

            comment.save()
            return HttpResponseRedirect (reverse ('posts:detail', args =( post_id , )))
    else :
        form = CommentForm ()
    context = {'form': form , 'post': post }
    return render (request , 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/category.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'posts/detail-category.html'

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/category.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Listas de Filmes</h2>
{% if category_list %}
<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'posts:detail-category' category.id %}"><h3>{{category.name}} (by {{ category.author }})</h3></a>
        </header>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma categoria.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar Filme {{ post.name }} ({{ post.release_year }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do filme</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Filme</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o filme "{{ post.name }} ({{ post.release_year }})"?
    </p>
    <button type="submit">Apagar</button>
    <p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do filme</a></p>
</form>

{% endblock content %}

posts/templates/posts/detail-category.html
{% extends 'base.html' %}

{% block title %}
Criar Filme
{% endblock title %}

{% block content %}
<h2>{{ category.name }}</h2>


{% csrf_token %}
<div class="lista-de-cards">
    {% for post in category.posts.all %}
    <div class="card">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.poster_url }}"
                alt="Poster do filme {{ post.name}}"></a>
        <p>{{ post.name }} ({{ post.release_year }})</p>
    </div>
    {% endfor %}
</div>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.release_year }}
{% endblock title %}

{% block content %}
<h2>Sinopse do Filme {{ post.name }} ({{ post.release_year }})</h2>

<section class="dados-de-filme">
    <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}">
    <ul>
        <li>Nome do Filme: {{ post.name }}</li>
        <li>Ano de Lançamento: {{ post.release_year }} </li>
        <li>Distributed by: {{ post.distribut}}</li>
        <br/>
        <li>{{post.synopsis}}</li>
        <br/>
        <li >Atualizado em: {{post.datepost}}</li>
        <li>Categorias:</li>
            {% if post.category_set.all %}
                {% for category in post.category_set.all %}
                    <li class='category'><a href="{% url 'posts:detail-category' category.id %}"><span style="color: #660000;">{{ category.name }}</span></a></li>
                {% endfor %}
            {% endif %}
        <br/>   
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha para este filme.</p>
        {% endif %}
    </ul>

    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Crie sua Resenha</button></a>
</section>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Filmes</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Filmes</a></p>
    <p>Não encontrou o filme? <a href="{% url 'posts:create' %}">Adicionar Novo Filme</a></p>
</section>
{% if post_list %}
    <section class="lista-de-cards">
        {% for post in post_list %}
        <article class="card">
            <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.poster_url }}"alt="Poster do filme {{ post.name}}"></a>
            <p>{{ post.name }} ({{ post.release_year }})</p>
        </article>
        {% endfor %}
    </section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}">
        <p>{{ post.name }} ({{ post.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme natalino para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Filme {{ post.name }}({{ post.release_year}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Assista esse filme!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.png' %}" height="180" width="170"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Filmes</a></li>
                <li><a href="{% url 'posts:category' %}">Listas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Site destinado para fãs de filmes natalinos comentarem seus filmes favoritos e criarem listas de recomendação</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Christmas Movies</i></h1>
<p>Discuta sobre seus filmes natalinos preferidos!</p>
{% endblock content %}

</html>